---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: harvester-homelab
  namespace: default-ubuntu-2404
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/mkenkel/harvester-homelab
