#cloud-config
hostname: ubuntu-vm
fqdn: ubuntu-vm.local

# User setup
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC... # Replace with your SSH public key

# Package updates and installation
package_update: true
package_upgrade: true

packages:
  - qemu-guest-agent
  - curl
  - wget
  - vim
  - htop
  - net-tools
  - openssh-server

# Services to enable
runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - systemctl enable ssh
  - systemctl start ssh

# Network configuration
network:
  version: 2
  ethernets:
    ens3:
      dhcp4: true

# Timezone
timezone: UTC

# Final message
final_message: "The system is finally up, after $UPTIME seconds"